spring:
  application:
     name: shop
  data:
    mongodb:
      host: localhost
      port: 27017
      database: shop     
  mvc:
    view:
      suffix: .jsp
      prefix: /views/
server:
  error:
    whitelabel:
      enabled: true 
      
security:
  oauth2:
    client:
      client-id: gOJlLIuZRtFXDo360ex7qTEY1xEi7A149aDieG6VoH
      client-secret: MUOXudbPCfm6NsWamj5AEHnlwseDHu6rQMxo2V8Ap9
      grant-type: client_credentials
      access-token-uri: https://api.molt.in/oauth/access_token
      client-authentication-scheme: header