spring:
  application:
     name: shop
  data:
    mongodb:
      host: ${MONGODB_HOST}
      port: ${MONGODB_PORT}
      database: ${MONGODB_DATABASE}  
      username: ${MONGODB_USER}
      password: ${MONGODB_PWD}
  mvc:
    view:
      suffix: .jsp
      prefix: /views/
server:
  error:
    whitelabel:
      enabled: true 
      
security:
  oauth2:
    client:
      client-id: ${SECURITY_OAUTH2_CLIENT_ID}
      client-secret: ${SECURITY_OAUTH2_CLIENT_SECRET}
      grant-type: ${SECURITY_OAUTH2_CLIENT_GRANT_TYPE}
      access-token-uri: ${SECURITY_OAUTH2_CLIENT_ACCESS_TOKEN_URI}
      
logging.level:
  org.springframework.web: DEBUG
  org.hibernate: ERROR
  org.springframework.security: INFO
  
url:
  moltin:
    api:
      products: ${URL_MOLTIN_API_PRODUCTS}
      categories: ${URL_MOLTIN_API_CATEGORIES}
      products-search: ${URL_MOLTIN_API_PRODUCT_SEARCH}
      cart: ${URL_MOLTIN_API_CART}